name: Generate Coverage
on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - name: Generate coverage report
        run: node_modules/.bin/jest --config jest.json --coverage > coverage.json
      - name: Upload report
        run: node_modules/.bin/codecov --disable=gcov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
          CI: true
