name: Release

on:
  push:
    branches:
      - master
      - next

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Changes
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Installing dependencies
        run: yarn
      - name: Unit tests
        run: yarn test
      - name: Building
        run: yarn build
      - name: Generate Docs
        run: yarn docs
      - name: Release
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          CI: true
